### ISSUE TITLE
list of neighboring states is incorrect

### ISSUE THREAD

**Issue by bantic** [ubikuity/List-of-neighboring-states-for-each-US-state#5]
It only lists a single neighbor for Utah ("UT"), but there should be 5, I believe, ID, CO, AZ, NV, WY.

**Comment by ubikuity** [comment]
To avoid duplication of the data, I inserted the link between 2 states in one direction only:
I mean, I inserted in the list the couple "AZ-UT" but not "UT-AZ".

So with the list, you can see that the neighbors of "UT" state are:
AZ-UT
CO-UT
ID-UT
NM-UT (We can debate about this one, but it seems reasonable to define them as neighbors. See the map: http://theincidentaleconomist.com/wordpress/list-of-neighboring-states-with-stata-code/)
NV-UT
UT-WY

**Comment by bantic** [comment]
Ah, I see. My intuitive understanding was that the CSV would have one row for each directed edge, so there would be an "AZ,UT" (read "Arizona has Utah as a neighbor") as well as a "UT,AZ" ("Utah has Arizona as a neighbor") when I saw a series of entries all starting with "AL" at the start of the file. I thought the data had been corrupted, leaving out other symmetric state pairs. Thanks for the explanation.
