### ISSUE TITLE
Data incomplete/ unreliable

### ISSUE THREAD

**Issue by 224XS** [ubikuity/List-of-neighboring-states-for-each-US-state#6]
This is a good effort and it is appreciated.
However, the data are incomplete: e.g.
Georgia is bounded by TN,SC,NC but also, FL and AL

**Comment by ubikuity** [comment]
The data is accurate. The trick is: you need to check your State in both the first and the second column.
AL;GA
FL;GA
GA;NC
GA;SC
GA;TN
The goal is to avoid duplicating in the data ("AL;GA" and "GA;AL" because it exactly the same pair).
